<?php

use Magento\Checkout\Block\Cart\Item\Renderer;
use Magento\Framework\Escaper;

/**
 * @var Renderer $block
 * @var Escaper $escaper
 */

$_item = $block->getItem();
$product = $_item->getProduct();
$isVisibleProduct = $product->isVisibleInSiteVisibility();
$twoColumnsLayout = $_item->getTwoColumnsLayout();
?>
<tbody class="cart item">
    <tr class="item-info">
        <td data-th="<?= $escaper->escapeHtml(__('Item Image')) ?>" class="col item-img">
            <?php if ($block->hasProductUrl()) :?>
                <a href="<?= $escaper->escapeUrl($block->getProductUrl()) ?>"
                   title="<?= $escaper->escapeHtml($block->getProductName()) ?>"
                   tabindex="-1"
                   class="product-item-photo">
            <?php else :?>
                <span class="product-item-photo">
            <?php endif;?>
            <?= $block->getImage($block->getProductForThumbnail(), 'cart_page_product_thumbnail')->toHtml() ?>
            <?php if ($block->hasProductUrl()) :?>
                </a>
            <?php else :?>
                </span>
            <?php endif; ?>
        </td>

        <td data-th="<?= $escaper->escapeHtml(__('Item Description')) ?>" class="col item-desc">
            <div class="product-item-details">
                <strong class="product-item-name">
                    <?php if ($block->hasProductUrl()) :?>
                        <a href="<?= $escaper->escapeUrl($block->getProductUrl()) ?>"><?= $escaper->escapeHtml($block->getProductName()) ?></a>
                    <?php else :?>
                        <?= $escaper->escapeHtml($block->getProductName()) ?>
                    <?php endif; ?>
                </strong>
                <?php if ($_options = $block->getOptionList()) :?>
                    <dl class="item-options">
                        <?php foreach ($_options as $_option) :?>
                            <?php $_formatedOptionValue = $block->getFormatedOptionValue($_option) ?>
                            <dt><?= $escaper->escapeHtml($_option['label']) ?></dt>
                            <dd>
                                <?php if (isset($_formatedOptionValue['full_view'])) :?>
                                    <?= $escaper->escapeHtml($_formatedOptionValue['full_view']) ?>
                                <?php else :?>
                                    <?= $escaper->escapeHtml($_formatedOptionValue['value'], ['span', 'a']) ?>
                                <?php endif; ?>
                            </dd>
                        <?php endforeach; ?>
                    </dl>
                <?php endif;?>
                <?php if ($messages = $block->getMessages()) :?>
                    <?php foreach ($messages as $message) :?>
                        <div class= "cart item message <?= $escaper->escapeHtmlAttr($message['type']) ?>">
                            <div><?= $escaper->escapeHtml($message['text']) ?></div>
                        </div>
                    <?php endforeach; ?>
                <?php endif; ?>
                <?php $addInfoBlock = $block->getProductAdditionalInformationBlock(); ?>
                <?php if ($addInfoBlock) :?>
                    <?= $addInfoBlock->setItem($_item)->toHtml() ?>
                <?php endif;?>
            </div>
            <?php if ($twoColumnsLayout): ?>
                <div class="field qty">
                    <div class="control qty">
                        <label for="cart-<?= $escaper->escapeHtmlAttr($_item->getId()) ?>-qty">
                            <span id="dec-<?= $_item->getId() ?>" class="input-number-decrement" data-product-id="<?= $_item->getId() ?>">-</span>
                            <input id="cart-<?= $escaper->escapeHtmlAttr($_item->getId()) ?>-qty"
                                name="cart[<?= $escaper->escapeHtmlAttr($_item->getId()) ?>][qty]"
                                data-cart-item-id="<?= $escaper->escapeHtmlAttr($_item->getSku()) ?>"
                                data-cart-product-id="<?= $escaper->escapeHtmlAttr($_item->getId()) ?>"
                                data-cart-url-submit="<?= $escaper->escapeHtmlAttr($block->getUrl('checkout/sidebar/updateItemQty')) ?>"
                                value="<?= $escaper->escapeHtmlAttr($block->getQty()) ?>"
                                type="number"
                                size="4"
                                step="any"
                                title="<?= $escaper->escapeHtmlAttr(__('Qty')) ?>"
                                class="input-text qty"
                                data-validate="{required:true,'validate-greater-than-zero':true}"
                                data-role="cart-item-qty"/>
                            <span id="inc-<?= $_item->getId() ?>" class="input-number-increment" data-product-id="<?= $_item->getId() ?>">+</span>
                        </label>
                    </div>
                </div>
            <?php endif;?>
        </td>

        <?php if (!$twoColumnsLayout): ?>
            <td class="col qty" data-th="<?= $escaper->escapeHtml(__('Qty')) ?>">
                <div class="field qty">
                    <div
                        class="control qty"
                        data-mage-init='{
                            "Billmate_NwtBillmateCheckout/js/checkout/qtyAdjust": {}
                        }'
                    >
                        <label for="cart-<?= $escaper->escapeHtmlAttr($_item->getId()) ?>-qty">
                            <span
                                id="inc-<?= $_item->getId() ?>"
                                class="input-number-increment"
                                data-product-id="<?= $_item->getId() ?>"
                            >
                                +
                            </span>
                            <input id="cart-<?= $escaper->escapeHtmlAttr($_item->getId()) ?>-qty"
                                name="cart[<?= $escaper->escapeHtmlAttr($_item->getId()) ?>][qty]"
                                data-cart-sku="<?= $escaper->escapeHtmlAttr($_item->getSku()) ?>"
                                data-cart-product-id="<?= $escaper->escapeHtmlAttr($_item->getId()) ?>"
                                value="<?= $escaper->escapeHtmlAttr($block->getQty()) ?>"
                                type="number"
                                size="4"
                                step="any"
                                title="<?= $escaper->escapeHtmlAttr(__('Qty')) ?>"
                                class="input-text qty"
                                data-validate="{required:true,'validate-greater-than-zero':true}"
                                data-role="cart-item-qty"/>
                            <span
                                id="dec-<?= $_item->getId() ?>"
                                class="input-number-decrement"
                                data-product-id="<?= $_item->getId() ?>"
                            >
                                -
                            </span>
                        </label>
                    </div>
                </div>
            </td>
        <?php endif; ?>

        <td class="col price" data-th="<?= $escaper->escapeHtml(__('Price')) ?>">
            <div class="actions-toolbar">
                <?= /* @noEscape */ $block->getActions($_item) ?>
            </div>
            <?= $block->getUnitPriceHtml($_item) ?>
        </td>
    </tr>
</tbody>