<?php

use Magento\Framework\View\Element\Template;
use Magento\Framework\Escaper;
use Billmate\NwtBillmateCheckout\ViewModel\Checkout;
use Magento\Framework\View\TemplateEngine\Php;

/**
 * @var Template $block
 * @var Php $this
 * @var Escaper $escaper
 * @var Checkout $viewModel
 */

$viewModel = $block->getViewModel();

?>

<div class="billmate-iframe-wrapper">
    <strong class="billmate-heading"><?= __('Address and payment') ?></strong>
    <iframe
        id="billmateCheckoutIframe"
        name="billmateCheckoutIframe"
        title="<?= $escaper->escapeHtmlAttr(__('Billmate Checkout Window')) ?>"
        style="min-height:800px;"
        src="<?= /* @noEscape */ $viewModel->getIframeUrl()  ?>?activateJsEvents=1"
        scrolling="no"
        sandbox="allow-same-origin allow-scripts allow-modals allow-popups allow-forms allow-top-navigation"
        data-mage-init='{
            "Billmate_NwtBillmateCheckout/js/checkout/model/checkout-handler": {
                "purchaseInitializedHideTarget":"<?= /* @noEscape */ $block->getPurchaseInitializedHideTarget() ?>"
            }
        }'
    >
    </iframe>
</div>