<?php

use Magento\Framework\View\Element\Template;
use Magento\Framework\Escaper;
use Billmate\NwtBillmateCheckout\ViewModel\Checkout;

/**
 * @var Template $block
 * @var Escaper $escaper
 * @var Checkout $viewModel
 */

$viewModel = $block->getViewModel();

?>

<div class="billmate-iframe-wrapper">
    <strong class="billmate-heading"><?= $escaper->escapeHtml(__('Address and payment')) ?></strong>
    <iframe
        id="billmateCheckoutIframe"
        name="billmateCheckoutIframe"
        title="<?= $escaper->escapeHtmlAttr(__('Billmate Checkout Window')) ?>"
        style="min-height:800px;"
        src="<?= /* @noEscape */ $viewModel->getIframeUrl()  ?>?activateJsEvents=1"
        scrolling="no"
        sandbox="allow-same-origin allow-scripts allow-modals allow-popups allow-forms allow-top-navigation"
        data-mage-init='{
            "Billmate_NwtBillmateCheckout/js/checkout/model/checkout-handler": {
                "purchaseInitializedHideTarget":"<?= $escaper->escapeHtmlAttr($block->getPurchaseInitializedHideTarget()) ?>",
                "methodCode":"<?= $escaper->escapeHtmlAttr($viewModel->getPaymentMethodCode()) ?>",
                "methodTitle":"<?= $escaper->escapeHtmlAttr($viewModel->getPaymentMethodTitle()) ?>",
                "defaultErrorMessage":"<?= $escaper->escapeHtmlAttr(__($block->getDefaultErrorMessage())) ?>"
            }
        }'
    >
    </iframe>
</div>