<?php
use Magento\Framework\View\Element\Template;
use Magento\Framework\Escaper;

/**
 * @var Template $block
 * @var Escaper $escaper
 */
?>
<div id="dibs-easy-checkout_newsletter" class="dibs-easy-checkout-block newsletter">
    <form 
        method="post"
        action="<?= $escaper->escapeHtmlAttr($block->getUrl('billmate/checkout/subscibeNewsletter')); ?>"
        id="dibs-easy-checkout-newsletter-form"
    >
        <div class="fieldset comment">
            <input 
                type="checkbox"
                name="newsletter"
                value="1"
                id="newsletter"
                title="<?= $escaper->escapeHtmlAttr(__('Subscribe To Our Newsletter')) ?>" class="checkbox"/>
            <label for="newsletter">
                <span class="tick"></span><?= $escaper->escapeHtml(__('Subscribe To Our Newsletter')) ?>
            </label>
        </div>
    </form>
</div>
