<?php 
/** 
 * @var $block \Billmate\NwtBillmateCheckout\Block\Success
*/

$orderId = $block->getOrderId();
$realId = $block->getRealOrderId();
?>
<div class="checkout-success cart-container" id="billmate-checkout-success">
    <?php if ($orderId): ?>
        <?php
            $orderData = $block->getOrderById($realId);
            $orderItems = $block->getOrderItems($realId);
        ?>
        <h3 class="billmate-success-heading">
            <?= __('Thank you for your purchase!') ?>
        </h3>
        <h3 class="billmate-success-heading">
            <?= __('We have received your order.') ?>
        </h3>
        <?php if ($orderData) : ?>
            <div class="billmate-checkout-grand-total amount">
                <span><?= $orderData->formatPrice($orderData->getData('grand_total')) ?></span>
            </div>
            <div class="order_inside">
                <ul class="billmate-checkout-order-overview billmate-checkout-thankyou-order-details order_details">
                    <li class="billmate-checkout-order-overview__order order">
                        <strong><?= __('Order number:') ?></strong>
                        <span>
                            <?php if ($block->getCanViewOrder()) : ?>
                                <span><?php echo __('#%1', sprintf('<a href="%s" class="order-number"><strong>%s</strong></a>', $block->escapeHtml($block->getViewOrderUrl()), $block->escapeHtml($block->getOrderId()))) ?></span>
                            <?php else : ?>
                                <span><?php echo __('#%1', $block->escapeHtml($block->getOrderId())) ?></span>
                            <?php endif; ?>
                        </span>
                    </li>

                    <li class="billmate-checkout-order-overview__date date">
                        <strong><?= __('Date:') ?></strong>
                        <span>
                            <?php
                                $date = substr($orderData->getData('created_at'), 0, 10);
                            ?>
                            <?= date("F j, Y", strtotime($date)); ?>
                        </span>
                    </li>
                    <li class="billmate-checkout-order-overview__total total billmate-mobile-hidden">
                        <strong><?= __('Total:') ?></strong>
                        <span>
                            <?= $orderData->formatPrice($orderData->getData('grand_total')) ?>
                        </span>
                    </li>
                    <li class="billmate-checkout-order-overview__payment-method method">
                        <strong><?= __('Payment method:') ?></strong> 
                        <span><?= __('Billmate checkout') ?></span>
                    </li>
                    <li class="billmate-checkout-order-overview__total total billmate-desktop-hidden">
                        <strong><?= __('Total:') ?></strong>
                        <span>
                            <?= $orderData->formatPrice($orderData->getData('grand_total')) ?>
                        </span>
                    </li>
                </ul>
            </div>
            <div class="logo-container">
                <img src="<?= $block->getViewFileUrl('Billmate_NwtBillmateCheckout::images/billmate-logo.svg'); ?>" alt="logo">
            </div>
            <?php if ($orderItems) : ?>
                <div class="billmate-checkout-order__items">
                    <h3 class="billmate-success-heading"><?= __('Order Details') ?></h3>
                <table>
                    <thead>
                        <tr>
                            <th class="col-item"><?= __('Product') ?></th>
                            <th class="col-subtotal"><?= __('Sum') ?></th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($orderItems as $orderItem) : ?>
                            <tr>
                                <td class="col-item" style="text-decoration:underline;"><?= $orderItem->getData('name') . ' <span class="count"> (x' . round($orderItem->getData('qty_ordered')) . ') </span >' ?></td>
                                <td class="col-amount"><?= $orderData->formatPrice($orderItem->getData('row_total_incl_tax')) ?></td>
                            </tr>
                        <?php endforeach; ?>
                        <?php if ($orderData->getData('discount_amount') > 0) : ?>
                            <tr>
                                <td class="col-item"><?= __('Discount:') ?></td>
                                <td class="col-amount"><?= $orderData->formatPrice($orderData->formatPrice($orderData->getData('discount_amount'))) ?></td>
                            </tr>
                        <?php endif; ?>
                        <tr>
                            <td class="col-item"><?= __('Shipping:') ?></td>
                            <td class="col-amount"><?= $orderData->formatPrice($orderData->getData('shipping_amount')) . '<span class="count"> (' . __('via ') . $orderData->getData('shipping_description') . ')</span >' ?></td>
                        </tr>
                        <tr>
                            <td class="col-item"><?= __('Payment Method:') ?></td>
                            <td class="col-amount"><?= __('Billmate checkout') ?></td>
                        </tr>
                        <tr>
                            <td class="col-item"><?= __('Total sum') ?>:</td>
                            <td class="col-amount"><?= $orderData->formatPrice($orderData->getData('grand_total')) ?></td>
                        </tr>
                    </tbody>
                </table>
            <?php endif; ?>

        <?php endif; ?>
        </div>
    <?php endif; ?>
    <div class="actions-toolbar">
        <div class="billmate-primary-wrapper">
            <a class="action primary billmate-btn continue" href="<?php /* @escapeNotVerified */
            echo $block->getUrl() ?>"><span><?php /* @escapeNotVerified */
                    echo __('Continue Shopping') ?></span></a>
        </div>
    </div>
</div>