<?php

use Magento\Framework\Escaper;
use Magento\Weee\Block\Item\Price\Renderer;

/**
 * @var Renderer $block
 * @var Escaper $escaper
 */

$item = $block->getItem();
$rowTotalExclTax = $block->getRowDisplayPriceExclTax();
$rowTotalInclTax = $block->getRowDisplayPriceInclTax();
$componentName = "billmate-checkout-itemid-{$item->getId()}-subtotal";
$koBlock = $block->getChildBlock('ko-viewmodel');

$koOutput = null;
if ($koBlock) {
    $koBlock->setRendererBlock($block);
    $koOutput = $item->getBillmateProcess() ? '' : $koBlock->toHtml();
}
?>

<?= /* @noEscape */ $koOutput ?>

<span class="subtotal-container" data-bind="scope: '<?= $escaper->escapeHtmlAttr($componentName) ?>'">
    <?php if (($block->displayPriceInclTax() || $block->displayBothPrices()) && !$item->getNoSubtotal()): ?>
        <span class="price-including-tax" data-label="<?= $escaper->escapeHtmlAttr(__('Incl. Tax')) ?>">
            <span class="cart-price">
                <?= /* @noEscape */ $block->setDataBindType('row_total_incl_tax')->formatPrice($rowTotalInclTax) ?>
            </span>
        </span>
    <?php endif; ?>

    <?php if ($block->displayPriceExclTax() || $block->displayBothPrices()): ?>
        <span class="price-excluding-tax" data-label="<?= $escaper->escapeHtmlAttr(__('Excl. Tax')) ?>">
            <span class="cart-price">
                    <?= /* @noEscape */ $block->setDataBindType('row_total')->formatPrice($rowTotalExclTax) ?>
            </span>
        </span>
    <?php endif; ?>
</span>