<?php

use Magento\Catalog\ViewModel\Product\Listing\PreparePostData;
use Magento\Framework\App\ActionInterface;
use Magento\Catalog\Block\Product\AbstractProduct;
use Magento\Framework\View\Helper\SecureHtmlRenderer;
use Magento\Framework\Escaper;

/**
 * @var AbstractProduct $block
 * @var SecureHtmlRenderer $secureRenderer
 * @var Escaper $escaper
 */

?>

<?php
switch ($type = $block->getType()) {

    case 'crosssell-rule':
        /** @var \Magento\Catalog\Block\Product\ProductList\Crosssell $block */
        if ($exist = $block->hasItems()) {
            $type = 'crosssell';
            $class = $type;

            $image = 'billmate_cross_sell_products';
            $title = __('Add the following products');
            $items = $block->getItemCollection();

            $showAddTo = true;
            $showCart = true;
            $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
            $description = false;
            $canItemsAddToCart = false;
        }
        break;

    case 'crosssell':
        /** @var \Magento\Catalog\Block\Product\ProductList\Crosssell $block */
        if ($exist = count($block->getItems())) {
            $type = 'crosssell';
            $class = $type;

            $image = 'cart_cross_sell_products';
            $title = __('Add the following products');
            $items = $block->getItems();

            $showAddTo = true;
            $showCart = true;
            $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
            $description = false;
            $canItemsAddToCart = false;
        }
        break;

    default:
        $exist = null;
}
$_item = null;
?>

<?php if ($exist):?>
    <div class="block <?= $escaper->escapeHtmlAttr($class) ?>">
        <div class="crosssell-wrapper">
            <div class="billmate-heading">
                <strong id="block-<?= $escaper->escapeHtmlAttr($class) ?>-heading" role="heading"
                        aria-level="2"><?= $escaper->escapeHtml($title) ?></strong>
            </div>
            <div class="block-content content" aria-labelledby="block-<?= $escaper->escapeHtmlAttr($class) ?>-heading">
                <div class="products wrapper grid products-grid products-<?= $escaper->escapeHtmlAttr($type) ?>">
                    <ol class="products list items product-items billmate-crosssell">
                        <?php foreach ($items as $_item):?>
                            <?php $available = ''; ?>
                            <li class="item product product-item">
                                <div class="product-item-info <?= /* @noEscape */ $available ?>">
                                    <?= /* @noEscape */ '<!-- ' . $image . '-->' ?>
                                    <a href="<?= $escaper->escapeUrl($block->getProductUrl($_item)) ?>"
                                        class="product photo product-item-photo">
                                        <?= $block->getImage($_item, $image)->toHtml() ?>
                                    </a>
                                    <div class="product details product-item-details">
                                        <strong class="product name product-item-name"><a
                                                    class="product-item-link"
                                                    title="<?= $escaper->escapeHtmlAttr($_item->getName()) ?>"
                                                    href="<?= $escaper->escapeUrl($block->getProductUrl($_item)) ?>">
                                                <?= $escaper->escapeHtml($_item->getName()) ?></a>
                                        </strong>

                                        <?= /* @noEscape */ $block->getProductPrice($_item) ?>

                                        <?php if ($showAddTo || $showCart): ?>
                                            <?php // phpcs:disable ?>
                                            <div class="product actions product-item-actions">
                                                <?php if ($showCart):?>
                                                    <div class="actions-primary">
                                                    <?php if ($_item->isSaleable()):?>
                                                        <?php if (!$_item->getTypeInstance()->isPossibleBuyFromList($_item)):?>
                                                            <button
                                                                    class="action tocart primary"
                                                                    data-mage-init='{"redirectUrl": {"url": "<?= $escaper->escapeUrl($block->getAddToCartUrl($_item)) ?>"}}' type="button" title="<?= $escaper->escapeHtmlAttr(__('Add to cart')) ?>">
                                                                <span><?= $escaper->escapeHtml(__('Add to cart')) ?></span>
                                                            </button>
                                                        <?php else :?>
                                                            <?php
                                                            /** @var $viewModel PreparePostData */
                                                            $viewModel = $block->getViewModel();
                                                            $postArray = $viewModel->getPostData(
                                                                $escaper->escapeUrl($block->getAddToCartUrl($_item)),
                                                                ['product' => $_item->getEntityId()]
                                                            );
                                                            $value = $postArray['data'][ActionInterface::PARAM_NAME_URL_ENCODED];
                                                            ?>
                                                            <form data-role="tocart-form"
                                                                    data-product-sku="<?= $escaper->escapeHtmlAttr($_item->getSku()) ?>"
                                                                    action="<?= $escaper->escapeUrl($block->getAddToCartUrl($_item)) ?>"
                                                                    method="post">
                                                                <input type="hidden" name="product"
                                                                        value="<?= /* @noEscape */ (int)$_item->getEntityId() ?>">
                                                                <input type="hidden"
                                                                        name="<?= /* @noEscape */ ActionInterface::PARAM_NAME_URL_ENCODED?>"
                                                                        value="<?= /* @noEscape */ $value ?>">
                                                                <?= $block->getBlockHtml('formkey') ?>
                                                                <button type="submit"
                                                                        title="<?= $escaper->escapeHtmlAttr(__('Add to cart')) ?>"
                                                                        class="action tocart primary">
                                                                    <span><?= $escaper->escapeHtml(__('Add to cart')) ?></span>
                                                                </button>
                                                            </form>
                                                        <?php endif; ?>
                                                    <?php else:?>
                                                        <?php if ($_item->getIsSalable()):?>
                                                            <div class="stock available">
                                                                <span><?= $escaper->escapeHtml(__('In stock')) ?></span>
                                                            </div>
                                                        <?php else:?>
                                                            <div class="stock unavailable">
                                                                <span><?= $escaper->escapeHtml(__('Out of stock')) ?></span>
                                                            </div>
                                                        <?php endif; ?>
                                                    <?php endif; ?>
                                                    </div>
                                                <?php endif; ?>
                                            </div>
                                            <?php // phpcs:enable ?>
                                        <?php endif; ?>
                                    </div>
                                </div>
                            </li>
                        <?php endforeach ?>
                    </ol>
                </div>
            </div>
        </div>
    </div>
    <?php if (!$block->isRedirectToCartEnabled() && $_item):?>
        <script type="text/x-magento-init">
        {
            "[data-role=tocart-form], .form.map.checkout": {
                "catalogAddToCart": {
                    "product_sku": "<?= $escaper->escapeHtml($_item->getSku()) ?>"
                }
            }
        }
        </script>
    <?php endif;?>
    <script type="text/x-magento-init">
        {
            ".billmate-crosssell": {
                "Billmate_NwtBillmateCheckout/js/checkout/slickInit": {

                }
            }
        }
    </script>
<?php endif;?>
